version: '3.8'

services:
  app:
    build:
      context: ./laravel-api
    container_name: laravel-app
    ports:
      - "8000:9000"
    volumes:
      - ./laravel-api:/var/www
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    container_name: pg-database
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # interface de gerenciamento

volumes:
  pgdata:
